flowchart LR
    %% Client Connections
    subgraph Client["Client Connections"]
        C1["Client 1"]
        C2["Client ..."]
        C3["Client N"]
    end

    %% Single-threaded Server
    subgraph Server["Single-threaded Server"]
        subgraph CE1["Connection Engine"]
            IM["I/O Multiplexer"]
            EL["Event Loop"]
        end

        subgraph P["Protocol Handler"]
            RESP["RESP Parser/Encoder"]
        end

        subgraph CE2["Command Engine"]
            CMD["Command Router"]
            VAL["Input Validator"]
        end

        subgraph S["Storage Engine"]
            MM["Memory Manager"]
            DT["Data Types"]
            EV["Eviction Manager"]
            EXP["Expiration Manager"]
            subgraph AT["Available Types"]
                STR["Strings"]
                LST["Lists"]
            end
        end
    end

    %% Connections
    C1 <--> IM
    C2 <--> IM
    C3 <--> IM
    IM <--> EL
    EL <--> RESP
    RESP <--> CMD
    CMD <--> VAL
    VAL <--> MM
    MM <--> DT
    DT <--> STR
    DT <--> LST
    MM <--> EV
    MM <--> EXP
    EV <--> EXP
