[package]
name = "rudist"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "0.8", features = ["os-poll", "net"] }
log = "0.4"
env_logger = "0.9"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"